# Generated by Django 5.2.12 on 2026-04-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('path', models.CharField(max_length=500)),
                ('stack', models.CharField(blank=True, db_index=True, max_length=50)),
                ('category', models.CharField(db_index=True, default='pro', max_length=20)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('last_commit', models.TextField(blank=True)),
                ('last_commit_date', models.CharField(blank=True, max_length=40)),
                ('is_dirty', models.BooleanField(db_index=True, default=False)),
                ('has_git', models.BooleanField(db_index=True, default=False)),
                ('has_remote', models.BooleanField(default=False)),
                ('has_mugiwara', models.BooleanField(db_index=True, default=False)),
                ('commits_ahead', models.IntegerField(default=0)),
                ('commits_behind', models.IntegerField(default=0)),
                ('invocations', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('claude_session_count', models.IntegerField(default=0)),
                ('docs', models.JSONField(default=list)),
                ('doc_files', models.JSONField(default=list)),
                ('scanned_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-invocations', 'name'],
                'indexes': [models.Index(fields=['category', 'stack'], name='projects_categor_7641a8_idx'), models.Index(fields=['has_git', 'is_dirty'], name='projects_has_git_250c9d_idx')],
            },
        ),
    ]
