# Generated by Django 5.2.12 on 2026-03-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100, unique=True)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('model', models.CharField(max_length=50)),
                ('project', models.CharField(db_index=True, max_length=200)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('cache_creation_tokens', models.IntegerField(default=0)),
                ('cache_read_tokens', models.IntegerField(default=0)),
                ('cost', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'token_usage',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['project', 'timestamp'], name='idx_token_proj_ts'), models.Index(fields=['model', 'timestamp'], name='idx_token_model_ts')],
            },
        ),
    ]
