# Generated by Django 5.2.12 on 2026-04-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenusage',
            name='is_subagent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='tokenusage',
            name='parent_session_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tokenusage',
            name='machine',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='tokenusage',
            index=models.Index(fields=['is_subagent'], name='idx_token_subagent'),
        ),
        migrations.AddIndex(
            model_name='tokenusage',
            index=models.Index(fields=['parent_session_id'], name='idx_token_parent_sess'),
        ),
    ]
