# Generated by Django 5.2.12 on 2026-04-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_subagent_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(default='Pro Team', max_length=50)),
                ('limit_5h_tokens', models.BigIntegerField(default=0)),
                ('limit_weekly_tokens', models.BigIntegerField(default=0)),
                ('alert_5h_tokens', models.BigIntegerField(blank=True, null=True)),
                ('alert_weekly_tokens', models.BigIntegerField(blank=True, null=True)),
                ('alert_5h_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('alert_weekly_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Token Limit Configuration',
                'db_table': 'token_limit',
            },
        ),
    ]
