# Generated by Django 5.2.12 on 2026-03-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('total_invocations', models.IntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('unique_agents', models.IntegerField(default=0)),
                ('unique_projects', models.IntegerField(default=0)),
                ('top_agent', models.CharField(blank=True, default='', max_length=100)),
                ('top_project', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'daily_stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('event', models.CharField(default='session_start', max_length=50)),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('project', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.CharField(blank=True, default='pro', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sessions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(unique=True)),
                ('week_end', models.DateField()),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('html_path', models.CharField(blank=True, default='', max_length=500)),
                ('draft_id', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(default='generated', max_length=50)),
            ],
            options={
                'db_table': 'weekly_reports',
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='Invocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('event', models.CharField(default='agent_invocation', max_length=50)),
                ('agent', models.CharField(db_index=True, max_length=100)),
                ('tool', models.CharField(blank=True, default='', max_length=100)),
                ('args_preview', models.TextField(blank=True, default='')),
                ('output_summary', models.TextField(blank=True, default='')),
                ('session_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('is_pipeline', models.BooleanField(default=False)),
                ('trigger_file', models.TextField(blank=True, default='')),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('reason', models.TextField(blank=True, default='')),
                ('pipeline_detected', models.TextField(blank=True, default='')),
                ('project', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('category', models.CharField(blank=True, db_index=True, default='pro', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'invocations',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['project'], name='idx_inv_project'), models.Index(fields=['category'], name='idx_inv_category')],
                'unique_together': {('timestamp', 'session_id', 'event', 'agent')},
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('demande', models.TextField(blank=True, default='')),
                ('route', models.CharField(blank=True, default='', max_length=100)),
                ('route_agent', models.CharField(blank=True, default='', max_length=100)),
                ('confiance', models.CharField(blank=True, default='moyenne', max_length=20)),
                ('sujet', models.TextField(blank=True, default='')),
                ('projet', models.CharField(blank=True, default='', max_length=200)),
                ('resultat', models.CharField(blank=True, default='en-cours', max_length=50)),
                ('resultat_detail', models.TextField(blank=True, default='')),
                ('contexte', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='pro', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'memory',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='idx_mem_date'), models.Index(fields=['category'], name='idx_mem_category')],
            },
        ),
    ]
