# Generated by Django 5.2.12 on 2026-04-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_weeklyreport_email_html_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('preset', models.CharField(blank=True, default='', max_length=30)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('html_path', models.CharField(blank=True, default='', max_length=500)),
                ('email_html_path', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(default='generated', max_length=50)),
            ],
            options={
                'db_table': 'custom_reports',
                'ordering': ['-generated_at', '-start_date'],
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='custom_repo_start_d_23b85c_idx')],
            },
        ),
    ]
