#!/bin/bash
# ============================================================
# Mugiwara Agents - Crew Registry (Single Source of Truth)
# All agent names and roles defined once, used everywhere
# ============================================================

CREW=(zorro sanji sanji-dotnet sanji-flutter sanji-python sanji-ts sanji-rust sanji-go sanji-java sanji-design sanji-i18n nami luffy franky robin chopper brook usopp jinbe yamato vegapunk shanks vivi ace law law-sql bartholomew perona senor-pink morgans morgans-release morgans-info morgans-rfp morgans-ticket monitoring feature-flags api-postman incident pre-launch onboard modernize mugiwara discovery doc-hunt one_piece bon-clay docker firebase iis infra-reseau iceburg sabo paulie coby enel ivankov thousand-sunny merry polar-tang oro-jackson baratie pluton ohara maxim crocodile doflamingo kizaru fujitora katakuri big-mom hawkins magellan caesar aokiji rayleigh prod-listener poneglyph azure a11y mlops agile bi dba chaos gcp smoker glpi)

ROLES=(
    "Business Analyst"
    "Architect & Tech Lead"
    "Sous-Chef C#/.NET"
    "Sous-Chef Flutter/Dart"
    "Sous-Chef Python"
    "Sous-Chef TypeScript/Node.js"
    "Sous-Chef Rust"
    "Sous-Chef Go"
    "Sous-Chef Java/Kotlin"
    "Sous-Chef Design & UI/UX"
    "Sous-Chef Traduction & i18n"
    "QA Lead"
    "Captain / Program Manager"
    "Code Reviewer"
    "System Cartographer"
    "Debugger & Diagnostician"
    "Technical Writer"
    "DevOps & IaC"
    "SecOps & Compliance"
    "Tech Intelligence & Dashboard"
    "Meta-Auditor & Agent Engineer"
    "Refactoring & Migration Expert"
    "Product Manager & UX"
    "Performance Engineer"
    "Data Engineer & Analytics"
    "SQL Specialist & Doc-to-SQL Converter"
    "Local API Analyzer"
    "Postman Collection Creator"
    "E2E Test Collection Creator"
    "Big News Communication Hub"
    "Sous-Agent Release (Attach)"
    "Sous-Agent Information (Sterry)"
    "Sous-Agent RFP (Vander Decken IX)"
    "Sous-Agent Ticketing (Absalom)"
    "Monitoring & Alerting [alias: enel]"
    "Feature Flags [alias: ivankov]"
    "Pipeline: API [alias: maxim]"
    "Pipeline: Incident [alias: polar-tang]"
    "Pipeline: Pre-Launch [alias: oro-jackson]"
    "Pipeline: Onboarding [alias: baratie]"
    "Pipeline: Modernization [alias: pluton]"
    "Full Pipeline [alias: thousand-sunny]"
    "Pipeline: Discovery [alias: merry]"
    "Pipeline: Doc Hunting [alias: ohara]"
    "Smart Router"
    "... 🤫"
    "Docker & Containerization"
    "Firebase & Google Cloud"
    "IIS & Windows Server"
    "Infrastructure Reseau"
    "Iceburg — Maitre Charpentier Docker"
    "Sabo — Chef Revolutionnaire Firebase"
    "Paulie — Charpentier IIS"
    "Coby — Capitaine Reseau"
    "Enel — Dieu Omniscient Monitoring"
    "Ivankov — Revolutionnaire Feature Flags"
    "Thousand Sunny — Pipeline Principal"
    "Merry — Pipeline Decouverte"
    "Polar Tang — Pipeline Incident"
    "Oro Jackson — Pipeline Pre-Launch"
    "Baratie — Pipeline Onboarding"
    "Pluton — Pipeline Modernisation"
    "Ohara — Pipeline Documentation"
    "Maxim — Pipeline API Postman"
    "Crocodile — Cloud AWS"
    "Doflamingo — Event-Driven Architecture"
    "Kizaru — Cloud Azure"
    "Fujitora — Accessibilite a11y"
    "Katakuri — AI/ML Ops"
    "Big Mom — Agile Coach & Scrum Master"
    "Hawkins — BI & Data Visualization"
    "Magellan — DBA (Database Admin)"
    "Caesar — Chaos Engineering"
    "Aokiji — Cloud GCP"
    "Rayleigh — Sentinelle de Production"
    "Prod Listener [alias: rayleigh]"
    "Poneglyph — Analyste de Documents"
    "Cloud Azure [alias: kizaru]"
    "Accessibilite a11y [alias: fujitora]"
    "AI/ML Ops [alias: katakuri]"
    "Agile Coach [alias: big-mom]"
    "BI & Data Visualization [alias: hawkins]"
    "DBA [alias: magellan]"
    "Chaos Engineering [alias: caesar]"
    "Cloud GCP [alias: aokiji]"
    "Smoker — Chasseur de Tickets GLPI"
    "GLPI Ticketing [alias: smoker]"
)
